from django.db import models
from datetime import datetime

# Create your models here.

class DateMixing:
    created = models.DateTimeField(default=datetime.utcnow)
    updated = models.DateTimeField(default=datetime.utcnow)

class Organizacoes(DateMixing, models.Model):
    __tablename__ = 'organizacoes'
    __table_args__ = {'schema': 'pipedrive'}

    id = models.IntegerField(primary_key=True)
    nome = models.CharField(max_length=200, null=True)
    etiqueta = models.CharField(max_length=200, null=True)
    org_endereco = models.CharField(max_length=200, null=True)
    org_pessoas = models.IntegerField(null=True)
    negocios_fechados = models.IntegerField(null=True)
    negocios_em_aberto = models.IntegerField(null=True)
    proxima_atividade = models.CharField(max_length=200, null=True)
    proprietario = models.CharField(max_length=200, null=True)
    org_tempo_funcionando = models.CharField(max_length=200, null=True)
    atividades_concluidas = models.CharField(max_length=200, null=True)
    atividades_fazer = models.CharField(max_length=200, null=True)
    cnpj = models.CharField(max_length=200, null=True)
    data_atualizada = models.DateTimeField(null=True)
    data_ultima_atividade = models.DateField(null=True)
    org_comprava_de = models.CharField(max_length=200, null=True)
    org_dias_pedido_semanais = models.CharField(max_length=200, null=True)
    endereco_mesmo_da_loja = models.CharField(max_length=200 , null=True)
    org_horario_recebe_min = models.TimeField(null=True)
    fuso_horario_min = models.CharField(max_length=200 , null=True)
    org_horario_recebe_max = models.TimeField(null=True)
    fuso_horario_max = models.CharField(max_length=200, null=True)
    inscricao_estadual = models.CharField(max_length=200, null=True)
    negocios_ganhos = models.IntegerField(null=True)
    negocios_perdidos = models.IntegerField(null=True)
    numero_mensagens_email = models.IntegerField(null=True)
    organizacao_criada = models.CharField(max_length=200, null=True)
    prazo_pagamento = models.CharField(max_length=200, null=True)
    org_item_mais_pedido1 = models.CharField(max_length=200, null=True)
    org_item_mais_pedido2 = models.CharField(max_length=200, null=True)
    org_item_mais_pedido3 = models.CharField(max_length=200, null=True)
    org_atendimento_tipo = models.CharField(max_length=200, null=True)
    ticket_medio_pessoa = models.CharField(max_length=200, null=True)
    org_tipo_cozinha = models.CharField(max_length=200, null=True)
    pratos_servidos_diariamente = models.CharField(max_length=200, null=True)
    razao_social = models.CharField(max_length=200, null=True)
    caso_contrario_completar = models.CharField(max_length=200, null=True)
    org_tem_delivery = models.CharField(max_length=200, null=True)
    total_atividades = models.IntegerField(null=True)
    valor_gasto_mensal = models.FloatField(max_length=200, null=True)
    moeda = models.CharField(max_length=200, null=True)
    visivel_para = models.CharField(max_length=200, null=True)
    org_area = models.CharField(max_length=200, null=True)
    cidade = models.CharField(max_length=200, null=True)
    estado_municipio = models.CharField(max_length=200, null=True)
    regiao = models.CharField(max_length=200, null=True)
    pais = models.CharField(max_length=200, null=True)
    cep = models.CharField(max_length=200, null=True)
    endereco_completo = models.CharField(max_length=200, null=True)
    apartamento_suite = models.CharField(max_length=200, null=True)
    numero_casa = models.CharField(max_length=200, null=True)
    logradouro = models.CharField(max_length=200, null=True)
    distrito_sublocalidade = models.CharField(max_length=200, null=True)



class Negocios(DateMixing, models.Model):
    __tablename__ = 'negocios'
    __table_args__ = {'schema': 'pipedrive'}

    id = models.IntegerField(primary_key=True)
    id_organizacao = models.ForeignKey("Organizacoes", on_delete=models.SET_NULL, null=True)
    funil = models.CharField(max_length=200, null=True)
    titulo = models.CharField(max_length=200, null=True)
    horario_recebe_min = models.TimeField(null=True)
    horario_recebe_max = models.TimeField(null=True)
    area = models.CharField(max_length=200, null=True)
    pessoa_contato = models.CharField(max_length=200, null=True)
    proprietario = models.CharField(max_length=200, null=True)
    valor = models.FloatField(null=True)
    tempo_funcionando = models.CharField(max_length=200, null=True)
    comprava_de = models.CharField(max_length=200, null=True)
    dias_pedido_semanais = models.CharField(max_length=200, null=True)
    pessoas = models.CharField(max_length=200, null=True)
    item_mais_pedido1 = models.CharField(max_length=200, null=True)
    item_mais_pedido2 = models.CharField(max_length=200, null=True)
    item_mais_pedido3 = models.CharField(max_length=200, null=True)
    atendimento_tipo = models.CharField(max_length=200, null=True)
    tipo_cozinha = models.CharField(max_length=200, null=True)
    tem_delivery = models.CharField(max_length=200, null=True)
    valor_produtos = models.CharField(max_length=200, null=True)
    endereco = models.CharField(max_length=200, null=True)
    ganho_em = models.DateTimeField(null=True)
    atividades_concluidas = models.CharField(max_length=200, null=True)
    atividades_a_fazer = models.CharField(max_length=200, null=True)
    como_conheceu = models.CharField(max_length=200, null=True)
    criador = models.CharField(max_length=200, null=True)
    data_atualizada = models.DateTimeField(null=True)
    data_proxima_atividade = models.DateTimeField(null=True)
    data_ultima_atividade = models.DateField(null=True)
    data_fechamento_esperada = models.DateField(null=True)
    etapa = models.CharField(max_length=200, null=True)
    data_perda = models.DateTimeField(null=True)
    etiqueta = models.CharField(max_length=200, null=True)
    motivo_perda = models.CharField(max_length=200, null=True)
    negocio_criado_em = models.DateTimeField(null=True)
    negocio_fechado_em = models.DateTimeField(null=True)
    num_mensagens_email = models.CharField(max_length=200, null=True)
    organizacao = models.CharField(max_length=200, null=True)
    pq_parou = models.CharField(max_length=200, null=True)
    probabilidade = models.CharField(max_length=200, null=True)
    qtd_produtos = models.IntegerField(null=True)
    status = models.CharField(max_length=200, null=True)
    total_atividades = models.IntegerField(null=True)
    valor_ponderado = models.FloatField(null=True)
    visivel_para = models.CharField(max_length=200, null=True)
    moeda = models.CharField(max_length=200, null=True)
    ultima_alteracao_etapa = models.DateTimeField(null=True)
    ultimo_email_enviado = models.DateTimeField(null=True)
    ultimo_email_recebido = models.DateTimeField(null=True)


class Atividades(DateMixing, models.Model):
    __tablename__ = 'atividades'
    __table_args__ = {'schema': 'pipedrive'}

    id = models.IntegerField(primary_key=True)
    id_negocios = models.ForeignKey("Negocios", on_delete=models.SET_NULL, null=True)
    concluido = models.CharField(max_length=200, null=True)
    assunto = models.CharField(max_length=200, null=True)
    negocio_nome = models.CharField(max_length=200, null=True)
    pessoa_contato = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    telefone = models.CharField(max_length=200, null=True)
    organizacao = models.CharField(max_length=200, null=True)
    data_vencimento = models.DateTimeField(null=True)
    duracao = models.CharField(max_length=200, null=True)
    atribuido_a_usuario = models.CharField(max_length=200, null=True)
    criador = models.CharField(max_length=200, null=True)
    data_adicionada = models.DateTimeField(null=True)
    data_atualizada = models.DateTimeField(null=True)
    descricao_publica = models.CharField(max_length=200, null=True)
    hora_ultima_notificacao = models.CharField(max_length=200, null=True)
    lead = models.CharField(max_length=200, null=True)
    livre_ocupado = models.CharField(max_length=200, null=True)
    localizacao = models.CharField(max_length=200, null=True)
    marcado_como_feito = models.CharField(max_length=200, null=True)
    nota = models.CharField(max_length=200, null=True)
    tipo = models.CharField(max_length=200, null=True)
